import { useQuery } from '@tanstack/react-query';
import { Activity as ActivityIcon, ArrowRight, Building2, CalendarClock, CircleDollarSign, ContactRound, Gauge, ListTodo, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { dashboardApi } from '@/api/services';
import { Badge, Card, ErrorState, PageHeader, PageSkeleton } from '@/components/ui';
import { LEAD_STAGES } from '@/lib/constants';
import { cn, formatCurrency, formatDate, relativeTime } from '@/lib/utils';
import type { Activity, DashboardData } from '@/types';

const kpiConfig = [
  { key: 'wonValue', label: 'Won value', icon: CircleDollarSign, format: formatCurrency, tint: 'bg-brand-100 text-brand-700 dark:bg-brand-950 dark:text-brand-300' },
  { key: 'totalLeads', label: 'Total leads', icon: ContactRound, format: (v: number) => String(v), tint: 'bg-sky-100 text-sky-700 dark:bg-sky-950 dark:text-sky-300' },
  { key: 'conversionRate', label: 'Conversion rate', icon: Gauge, format: (v: number) => `${v}%`, tint: 'bg-violet-100 text-violet-700 dark:bg-violet-950 dark:text-violet-300' },
  { key: 'openTasks', label: 'Open tasks', icon: ListTodo, format: (v: number) => String(v), tint: 'bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300' },
] as const;

function KpiGrid({ data }: { data: DashboardData }) {
  return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{kpiConfig.map(({ key, label, icon: Icon, format, tint }) => <Card key={key} className="relative overflow-hidden bg-gradient-to-br from-white via-white to-brand-50/40 p-5 dark:from-ink-900 dark:via-ink-900 dark:to-brand-950/30"><div className="absolute inset-x-0 top-0 h-0.5 bg-gradient-to-r from-brand-500 to-sky-500" /><div className="flex items-start justify-between"><div className={cn('grid h-10 w-10 place-items-center rounded-lg', tint)}><Icon className="h-[19px] w-[19px]" /></div>{key === 'openTasks' && data.overdueTasks > 0 ? <Badge tone="danger">{data.overdueTasks} overdue</Badge> : <span className="text-xs font-medium text-ink-500">Updated</span>}</div><p className="mt-5 font-display text-2xl font-bold tracking-tight text-ink-950 dark:text-white">{format(data[key])}</p><p className="mt-1 text-sm font-medium text-ink-500 dark:text-ink-400">{label}</p></Card>)}</div>;
}

function PipelineTooltip({ active, payload, label }: { active?: boolean; payload?: Array<{ value: number; name: string; color: string }>; label?: string }) {
  if (!active || !payload?.length) return null;
  return <div className="rounded-xl border border-ink-200 bg-white p-3 shadow-lift dark:border-ink-700 dark:bg-ink-900"><p className="mb-2 text-xs font-bold text-ink-800 dark:text-white">{LEAD_STAGES.find((s) => s.value === label)?.label ?? label}</p>{payload.map((entry) => <div key={entry.name} className="flex min-w-32 items-center justify-between gap-4 text-xs"><span className="text-ink-500">{entry.name}</span><strong className="text-ink-800 dark:text-white">{entry.name === 'Value' ? formatCurrency(entry.value) : entry.value}</strong></div>)}</div>;
}

function ActivityRow({ activity }: { activity: Activity }) {
  const tone = activity.action.includes('DELETE') ? 'danger' : activity.action.includes('CREATE') ? 'info' : 'brand';
  return <div className="flex gap-3 py-3.5"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-xl bg-ink-100 text-ink-500 dark:bg-ink-800"><ActivityIcon className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="text-sm leading-5 text-ink-700 dark:text-ink-200">{activity.summary}</p><p className="mt-1 text-[11px] text-ink-500">{relativeTime(activity.createdAt)}</p></div><Badge tone={tone} className="h-fit">{activity.entityType?.toLowerCase() ?? 'record'}</Badge></div>;
}

export function DashboardPage() {
  const query = useQuery({ queryKey: ['dashboard'], queryFn: dashboardApi.get, staleTime: 60_000 });
  const activities = useQuery({ queryKey: ['activities', 'dashboard'], queryFn: () => dashboardApi.activities({ page: 0, size: 4 }) });
  if (query.isLoading) return <PageSkeleton />;
  if (query.isError || !query.data) return <ErrorState onRetry={() => void query.refetch()} description="The dashboard service is unavailable. Your data is safe—try again shortly." />;
  const data = query.data;
  const maxPipeline = Math.max(1, ...data.pipeline.map((stage) => stage.value));
  const activePercent = data.totalCustomers ? Math.round(data.activeCustomers / data.totalCustomers * 100) : 0;
  return <div className="space-y-6"><div className="enterprise-gradient rounded-2xl border border-brand-100 p-5 shadow-soft dark:border-brand-900 dark:bg-ink-900 dark:bg-none sm:p-6"><PageHeader eyebrow="Workspace pulse" title="Good morning — here’s your focus" description="A live view of pipeline health, customer momentum, and what needs attention." actions={<Link to="/app/leads" className="inline-flex h-11 items-center gap-2 rounded-lg bg-gradient-to-r from-brand-600 to-sky-700 px-4 text-sm font-semibold text-white shadow-sm hover:from-brand-700 hover:to-sky-800">Open pipeline <ArrowRight className="h-4 w-4" /></Link>} /></div><KpiGrid data={data} />
    <div className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><Card className="p-5 sm:p-6"><div className="flex items-start justify-between"><div><h2 className="font-display text-base font-bold text-ink-950 dark:text-white">Pipeline by stage</h2><p className="mt-1 text-xs text-ink-500">Current opportunity value and volume</p></div><Badge tone="brand">Live pipeline</Badge></div><div className="mt-6 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.pipeline} margin={{ left: -20, right: 8 }}><CartesianGrid strokeDasharray="4 5" vertical={false} stroke="#e2e8f0" /><XAxis dataKey="stage" axisLine={false} tickLine={false} tick={{ fill: '#64748b', fontSize: 11 }} tickFormatter={(stage) => LEAD_STAGES.find((s) => s.value === stage)?.label ?? stage} dy={8} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#64748b', fontSize: 11 }} tickFormatter={(v) => `$${v / 1000}k`} domain={[0, maxPipeline]} /><Tooltip cursor={{ fill: '#f1f5f9' }} content={<PipelineTooltip />} /><Bar dataKey="value" name="Value" radius={[5, 5, 0, 0]} barSize={28}>{data.pipeline.map((entry, index) => <Cell key={entry.stage} fill={['#0284c7', '#0891b2', '#0e7490', '#0d9488', '#0f766e', '#059669', '#e11d48'][index % 7]} />)}</Bar></BarChart></ResponsiveContainer></div><div className="mt-3 flex flex-wrap gap-3">{data.pipeline.map((stage) => <div key={stage.stage} className="flex items-center gap-1.5 text-xs text-ink-500"><i className={cn('h-2 w-2 rounded-full', LEAD_STAGES.find((s) => s.value === stage.stage)?.color)} />{LEAD_STAGES.find((s) => s.value === stage.stage)?.label}: <strong className="text-ink-700 dark:text-ink-200">{stage.count}</strong></div>)}</div></Card>
      <Card className="p-5 sm:p-6"><div className="flex items-start justify-between"><div><h2 className="font-display text-base font-bold text-ink-950 dark:text-white">Customer health</h2><p className="mt-1 text-xs text-ink-500">Active relationships in your tenant</p></div><Building2 className="h-5 w-5 text-brand-600" /></div><div className="mx-auto mt-8 grid h-40 w-40 place-items-center rounded-full" style={{ background: `conic-gradient(#0f7f78 ${activePercent * 3.6}deg, #e2e8f0 0deg)` }}><div className="grid h-[8.2rem] w-[8.2rem] place-items-center rounded-full bg-white text-center dark:bg-ink-900"><div><p className="font-display text-3xl font-bold text-ink-950 dark:text-white">{activePercent}%</p><p className="text-xs font-semibold uppercase tracking-wider text-ink-500">active</p></div></div></div><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-lg bg-brand-50 p-3 text-center dark:bg-brand-950/40"><p className="text-lg font-bold text-brand-800 dark:text-brand-200">{data.activeCustomers}</p><p className="text-xs text-brand-700 dark:text-brand-400">Active</p></div><div className="rounded-lg bg-ink-100 p-3 text-center dark:bg-ink-800"><p className="text-lg font-bold text-ink-800 dark:text-white">{data.totalCustomers}</p><p className="text-xs text-ink-500">Total</p></div></div></Card></div>
    <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><Card className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-display text-base font-bold text-ink-950 dark:text-white">Upcoming tasks</h2><p className="mt-1 text-xs text-ink-500">The next actions in due-date order</p></div><Link to="/app/tasks" className="text-xs font-bold text-brand-700 dark:text-brand-400">View all</Link></div><div className="mt-4 divide-y divide-ink-100 dark:divide-ink-800">{data.upcomingTasks.map((task) => <div key={task.id} className="flex items-center gap-3 py-3.5"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300"><CalendarClock className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-ink-900 dark:text-white">{task.title}</p><p className="mt-1 text-[11px] text-ink-500">Due {formatDate(task.dueAt, 'MMM d, h:mm a')}</p></div><Badge tone={task.priority === 'URGENT' ? 'danger' : task.priority === 'HIGH' ? 'warning' : 'neutral'}>{task.priority.toLowerCase()}</Badge></div>)}{!data.upcomingTasks.length && <p className="py-12 text-center text-sm text-ink-500">No upcoming tasks.</p>}</div></Card>
      <Card className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-display text-base font-bold text-ink-950 dark:text-white">Live activity</h2><p className="mt-1 text-xs text-ink-500">The latest across your workspace</p></div><Sparkles className="h-5 w-5 text-brand-500" /></div><div className="mt-3 divide-y divide-ink-100 dark:divide-ink-800">{activities.data?.content.map((activity: Activity) => <ActivityRow key={activity.id} activity={activity} />)}{activities.isError && <p className="py-10 text-center text-sm text-ink-500">Activity is temporarily unavailable.</p>}{!activities.isLoading && !activities.isError && !activities.data?.content.length && <p className="py-10 text-center text-sm text-ink-500">No recent activity yet.</p>}</div></Card></div>
  </div>;
}
